export const LOGIN_REQUEST = Symbol('LOGIN_REQUEST');
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');
export const LOGIN_FAILD = Symbol('LOGIN_FAILD');

export const REGISTRATION_REQUEST = Symbol('REGISTRATION_REQUEST');
export const REGISTRATION_SUCCESS = Symbol('REGISTRATION_SUCCESS');
export const REGISTRATION_FAILD = Symbol('REGISTRATION_FAILD');

export const LOGOUT_REQUEST = Symbol('LOGOUT_REQUEST');
export const LOGOUT_SUCCESS = Symbol('LOGOUT_SUCCESS');
export const LOGOUT_FAILD = Symbol('LOGOUT_FAILD');

export const SETUSERME_REQUEST = Symbol('SETUSERME_REQUEST');
export const SETUSERME_SUCCESS = Symbol('SETUSERME_SUCCESS');
export const SETUSERME_FAILD = Symbol('SETUSERME_FAILD');

export const RECIVEAUTH_REQUEST = Symbol('RECIVEAUTH_REQUEST');
export const RECIVEAUTH_SUCCESS = Symbol('RECIVEAUTH_SUCCESS');
export const RECIVEAUTH_FAILD = Symbol('RECIVEAUTH_FAILD');

export const REDIRECT = Symbol('REDIRECT');