export const GET_CHATITEM_REQUEST = Symbol('GET_CHATITEM_REQUEST');
export const GET_CHATITEM_SUCCESS = Symbol('GET_CHATITEM_SUCCESS');
export const GET_CHATITEM_FAILD = Symbol('GET_CHATITEM_FAILD');

export const CREATE_CHAT_REQUEST = Symbol('CREATE_CHAT_REQUEST');
export const CREATE_CHAT_SUCCESS = Symbol('CREATE_CHAT_SUCCESS');
export const CREATE_CHAT_FAILD = Symbol('CREATE_CHAT_FAILD');

export const GET_CHAT_MESSAGES_REQUEST = Symbol('GET_CHAT_MESSAGES_REQUEST');
export const GET_CHAT_MESSAGES_SUCCESS = Symbol('GET_CHAT_MESSAGES_SUCCESS');
export const GET_CHAT_MESSAGES_FAILD = Symbol('GET_CHAT_MESSAGES_FAILD');

export const SEND_MESSAGES_REQUEST = Symbol('SEND_MESSAGES_REQUEST');
export const SEND_MESSAGES_SUCCESS = Symbol('SEND_MESSAGES_SUCCESS');
export const SEND_MESSAGES_FAILD = Symbol('SEND_MESSAGES_FAILD');

export const DELTE_CHAT_REQUEST = Symbol('DELTE_CHAT_REQUEST');
export const DELTE_CHAT_SUCCESS = Symbol('DELTE_CHAT_SUCCESS');
export const DELTE_CHAT_FAILD = Symbol('DELTE_CHAT_FAILD');




export const FETCH_ALL_CHAT_REQUEST = Symbol('FETCH_ALL_CHAT_REQUEST');
export const FETCH_ALL_CHAT_SUCCESS = Symbol('FETCH_ALL_CHAT_SUCCESS');
export const FETCH_ALL_CHAT_FAILD = Symbol('FETCH_ALL_CHAT_FAILD');

export const FETCH_MY_CHAT_REQUEST = Symbol('FETCH_MY_CHAT_REQUEST');
export const FETCH_MY_CHAT_SUCCESS = Symbol('FETCH_MY_CHAT_SUCCESS');
export const FETCH_MY_CHAT_FAILD = Symbol('FETCH_MY_CHAT_FAILD');

export const SET_ACTIVE_CHAT = Symbol('SET_ACTIVE_CHAT');
export const UNSET_ACTIVE_CHAT = Symbol('UNSET_ACTIVE_CHAT');
